sudo: required
services:
  - docker
before_install:
  - docker build -t "$DOCKER_ID"/dk-fib-test -f ./client/Dockerfile.dev ./client
script:
  - docker run "$DOCKER_ID"/dk-fib-test npm run test -- --coverage
after_success:
  - docker build -t "$DOCKER_ID"/dk-fib-client ./client
  - docker build -t "$DOCKER_ID"/dk-fib-nginx ./nginx
  - docker build -t "$DOCKER_ID"/dk-fib-server ./server
  - docker build -t "$DOCKER_ID"/dk-fib-worker ./worker
  # take images and push to docker hub
  # 1. Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # 2. push images
  - docker push "$DOCKER_ID"/dk-fib-client
  - docker push "$DOCKER_ID"/dk-fib-nginx
  - docker push "$DOCKER_ID"/dk-fib-server
  - docker push "$DOCKER_ID"/dk-fib-worker
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: dk-fibonacci
  env: DkFibonacci-env
  bucket_name: elasticbeanstalk-us-west-1-722739487944
  bucket_path: dk-fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY