sudo: required
services:
  - docker
before_install:
  - docker build -t yehuizhang/dk-fib-test -f ./client/Dockerfile.dev ./client
script:
  - docker run yehuizhang/dk-fib-client-test npm run test -- --coverage
after_success:
  - docker build -t yehuizhang/dk-fib-client ./client
  - docker build -t yehuizhang/dk-fib-nginx ./nginx
  - docker build -t yehuizhang/dk-fib-server ./server
  - docker build -t yehuizhang/dk-fib-worker ./worker
  # take images and push to docker hub
  # 1. Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # 2. push images
  - docker push yehuizhang/dk-fib-client
  - docker push yehuizhang/dk-fib-nginx
  - docker push yehuizhang/dk-fib-server
  - docker push yehuizhang/dk-fib-worker


# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "dk-react"
#   env: "DkReact-env"
#   bucket_name: "elasticbeanstalk-us-west-1-722739487944"
#   bucket_path: "dk-react"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"